
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mms
  template:
    metadata:
      labels:
        app: mms
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - node-group # this value i have taken from my aws console  - ec2 - autoscaling group - details - tags (key==> eks:nodegroup-name value ===> node-group)
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - maanged 
            topologyKey: kubernetes.io/hostname
            namespaces:
            - default
      containers:
      - name: mms
        image: nodejs:latest
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 3030
        resources:
            limits:
              cpu: 900m
            requests:
              cpu: 250m
